ARG PYTHON_BUILD_IMAGE=cgr.dev/chainguard/python:latest-dev@sha256:1c830d26eef0eb4231d8c119e037bee325329aa0ac67c527a86d6e62c05d23d1
ARG PRODUCTION_IMAGE=mohankrishna999/portal-validator:1.1.0
FROM ${PYTHON_BUILD_IMAGE} AS debug-dependencies

USER 0
WORKDIR /build
COPY requirements.txt requirements-dev.txt ./
RUN python -m venv /debug-venv \
    && /debug-venv/bin/pip install --no-cache-dir --no-compile -r requirements.txt -r requirements-dev.txt \
    && /debug-venv/bin/pip uninstall -y pip setuptools
RUN find /debug-venv/bin -maxdepth 1 -type f \
    -exec sed -i '1s#/debug-venv#/app/.venv#' '{}' ';'

FROM ${PRODUCTION_IMAGE}

ENV MAX_CONCURRENT_SCANS=1

USER 0
WORKDIR /app
COPY --from=debug-dependencies /debug-venv /app/.venv
COPY --chown=10001:10001 app ./app

USER 10001:10001
EXPOSE 8080 5678
ENTRYPOINT []
CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
